### ISSUE TITLE
Unable to verify contract on Sepolia etherscan

### ISSUE THREAD

**Issue by nandorcsupor** [Cyfrin/foundry-fund-me-f23#8] opened 2023-06-15 17:50 UTC
I coded along -  but the Makefile is copied from github. 

ISSUE - I'm unable to get my contract verified when I'm deploying on Sepolia. It's obviously NOT critical, just wondering if anyone has any ideas about it ?
I got the API key from etherscan.io and they are supposed to work for all testnets as well.

Here is the stack trace:

```
`make deploy ARGS="--network sepolia"
[⠒] Compiling...
No files changed, compilation skipped
Traces:
  [1064837] DeployFundMe::run() 
    ├─ [508818] → new HelperConfig@0xC7f2Cf4845C6db0e1a1e91ED41Bcd0FcC1b0E141
    │   └─ ← 2209 bytes of code
    ├─ [359] HelperConfig::activeNetworkConfig() [staticcall]
    │   └─ ← 0x694AA1769357215DE4FAC081bf1f309aDC325306
    ├─ [0] VM::startBroadcast() 
    │   └─ ← ()
    ├─ [465485] → new FundMe@0xc525960E92163ef91a3057838Ea1DEf9EB1dfF54
    │   └─ ← 2213 bytes of code
    ├─ [0] VM::stopBroadcast() 
    │   └─ ← ()
    └─ ← FundMe: [0xc525960E92163ef91a3057838Ea1DEf9EB1dfF54]


Script ran successfully.

== Return ==
0: contract FundMe 0xc525960E92163ef91a3057838Ea1DEf9EB1dfF54

## Setting up (1) EVMs.
==========================
Simulated On-chain Traces:

  [554633] → new FundMe@0xc525960E92163ef91a3057838Ea1DEf9EB1dfF54
    └─ ← 2213 bytes of code


==========================

Chain 11155111

Estimated gas price: 5.932978292 gwei

Estimated total gas used for script: 721022

Estimated amount required: 0.004277807874054424 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].
⠁ [00:00:00] [#######################################################] 1/1 txes (0.0s)
Transactions saved to: /home/nandor/Solidity-06/foundry-fund-me/broadcast/DeployFundMe.s.sol/11155111/run-latest.json

Sensitive values saved to: /home/nandor/Solidity-06/foundry-fund-me/cache/DeployFundMe.s.sol/11155111/run-latest.json

##
Waiting for receipts.
⠉ [00:00:25] [###################################################] 1/1 receipts (0.0s)
##### sepolia
✅ Hash: 0xe7b8b07a532fd80f608dc74d87906599034a87524aa9a07ac94990e7191aee38
Contract Address: 0xc525960e92163ef91a3057838ea1def9eb1dff54
Block: 3698656
Paid: 0.00335535531606044 ETH (554785 gas * 6.048028184 gwei)


Transactions saved to: /home/nandor/Solidity-06/foundry-fund-me/broadcast/DeployFundMe.s.sol/11155111/run-latest.json

Sensitive values saved to: /home/nandor/Solidity-06/foundry-fund-me/cache/DeployFundMe.s.sol/11155111/run-latest.json



==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.00335535531606044 ETH (554785 gas * avg 6.048028184 gwei)
##
Start verification for (1) contracts
Start verifying contract `0xc525960e92163ef91a3057838ea1def9eb1dff54` deployed on sepolia

Submitting verification for [src/FundMe.sol:FundMe] "0xc525960E92163ef91a3057838Ea1DEf9EB1dfF54".

Submitting verification for [src/FundMe.sol:FundMe] "0xc525960E92163ef91a3057838Ea1DEf9EB1dfF54".
Submitted contract for verification:
        Response: `OK`
        GUID: `hbkdwvmews2zabsyzqqqy3vqggm45gxx6gqyuk6k9aikavrdbi`
        URL:
        https://sepolia.etherscan.io/address/0xc525960e92163ef91a3057838ea1def9eb1dff54
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Please check if the correct constructor argument was entered.`
Contract failed to verify.
make: *** [Makefile:43: deploy] Error 1`
```

**Comment by ShayanShamsi** [comment] 2023-06-18 20:03
Hey @nandorcsupor!
I checked your contract address on the chain explorer and looks like you haven't verified the contract yet.

I found [this issue in the foundry repo](https://github.com/foundry-rs/foundry/issues/5110) which _might be_ related. In the issue, user @0xPublicGoods made [this comment](https://github.com/foundry-rs/foundry/issues/5110#issuecomment-1585709474) which looks exactly like your problem since the user also encountered the same error while following the course.

If my guess is correct, it was an issue with Foundry and should be resolved after you run `foundryup` and then try verifying the contract.

If this does not help, let me know here and we will try solving the issue!

**Comment by PatrickAlphaC** [comment] 2023-06-18 21:30
confirmed, verification is buggy in foundry right now. They are working on a fix!

**Comment by ShayanShamsi** [comment] 2023-06-18 21:42
@PatrickAlphaC might be fixed by now since I verified my contract a few hours ago and the verification was successful

**Comment by praveenzsp** [comment] 2023-07-16 13:01
I am still facing the verification issue.

**Comment by dexv2** [comment] 2023-08-02 12:07
I'm also facing verification issue. In my case, the solidity version is concatenated with the contract name `src/FundMe.sol:FundMe.0.8.18` which could not be found. Here's the complete error:
```
ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.001696536534078675 ETH (563637 gas * avg 3.009980775 gwei)
##
Start verification for (1) contracts
Start verifying contract `0x84d77c36d486b41d0c4653056c7423e2ac36f98d` deployed on sepolia

Submitting verification for [src/FundMe.sol:FundMe.0.8.18] "0x84d77C36D486B41d0C4653056C7423e2Ac36F98D".
Submitted contract for verification:
        Response: `OK`
        GUID: `cvi1xgzsmrbv6xiktyiwjm6ubnlm5rbfxqigefdukr1qmds4kk`
        URL:
        https://sepolia.etherscan.io/address/0x84d77c36d486b41d0c4653056c7423e2ac36f98d
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Unable to locate a contract with the name 'src/FundMe.sol:FundMe.0.8.18', did you specify the correct Contract Name?`
Contract failed to verify.
make: *** [deploy-sepolia-resume] Error 1
```

**Comment by PatrickAlphaC** [comment] 2023-12-27 21:41
Closing. I think this is fixed now.

**Closed by PatrickAlphaC** 2023-12-27 21:41 UTC
